BlackJack.UI/Controllers/RoundController.cs
using BlackJack.BusinessLogic.Constants;
using BlackJack.BusinessLogic.Services.Interfaces;
using BlackJack.ViewModels.Round;
using NLog;
using System;
using System.Threading.Tasks;
using System.Web.Http;

namespace BlackJack.UI.Controllers
{
    [RoutePrefix("Round")]
    public class RoundController : ApiController
    {
        private static readonly Logger _logger = LogManager.GetCurrentClassLogger();
        private readonly IRoundService _roundService;

        public RoundController (IRoundService roundService)
        {
            _roundService = roundService;
        }
        
        [Route("Start"), HttpPost]
        public async Task<IHttpActionResult> Start(RequestStartRoundView requestView)
        {
            try
            {
                ResponseStartRoundView responseView = await _roundService.Start(requestView);
                return Ok(responseView);
            }
            catch (Exception exception)
            {
                string message = exception.ToString();
                _logger.Error(message);
                return BadRequest(GameMessage.GameProcessingError);
            }
        }
        
        [Route("TakeCard"), HttpGet]
        public async Task<IHttpActionResult> TakeCard(long gameId)
        {
            try
            {
                TakeCardRoundView view = await _roundService.TakeCard(gameId);
                return Ok(view);
            }
            catch (Exception exception)
            {
                string message = exception.ToString();
                _logger.Error(message);
                return BadRequest(GameMessage.GameProcessingError);
            }
        }
        
        [Route("End"), HttpGet]
        public async Task<IHttpActionResult> End(long gameId)
        {
            try
            {
                EndRoundView view = await _roundService.End(gameId);
                return Ok(view);
            }
            catch (Exception exception)
            {
                string message = exception.ToString();
                _logger.Error(message);
                return BadRequest(GameMessage.GameProcessingError);
            }
        }
    }
}

BlackJack.UI/Controllers/StartGameController.cs
using System;
using System.Web.Mvc;
using System.Threading.Tasks;
using BlackJack.BusinessLogic.Interfaces;
using BlackJack.BusinessLogic.Helpers;
using BlackJack.ViewModels.ViewModels.StartGame;
using NLog;

namespace BlackJack.UI.Controllers
{
    public class StartGameController : Controller
    {
        private static readonly Logger _logger = LogManager.GetCurrentClassLogger();
        private readonly IStartGameService _startGameService;


        public StartGameController (IStartGameService startGameService)
        {
            _startGameService = startGameService;
        }
        
        public ActionResult ValidateName()
        {
            StartGameValidateNameView startGameValidateNameView = new StartGameValidateNameView();
            return View(startGameValidateNameView);
        }

        [HttpPost]
        public async Task<ActionResult> ValidateName(StartGameValidateNameView startGameValidateNameView)
        {
            try
            {
                startGameValidateNameView.ValidationMessage = _startGameService.ValidatePlayerName(startGameValidateNameView.UserName);

                if(string.IsNullOrEmpty(startGameValidateNameView.ValidationMessage))
                {
                    await _startGameService.CreatePlayer(startGameValidateNameView.UserName);
                    return RedirectToAction("AuthorizePlayer", new { userName = startGameValidateNameView.UserName });
                }
                
                return View(startGameValidateNameView);
            }
            catch (Exception ex)
            {
                string message = $"{ex.Source}|{ex.TargetSite}|{ex.StackTrace}|{ex.Message}";
                _logger.Error(message);
                return RedirectToAction("Error", new { message = GameMessageHelper.PlayerAuthError });
            }
        }
        
        public async Task<ActionResult> AuthorizePlayer(string userName)
        {
            try
            {
                StartGameAuthorizePlayerView startGameAuthorizePlayerView = await _startGameService.AuthorizePlayer(userName);
                return View(startGameAuthorizePlayerView);
            }
            catch (Exception ex)
            {
                string message = $"{ex.Source}|{ex.TargetSite}|{ex.StackTrace}|{ex.Message}";
                _logger.Error(message);
                return RedirectToAction("Error", new { message = GameMessageHelper.PlayerAuthError });
            }
        }

        [HttpPost]
        public async Task<ActionResult> StartNewGame(long playerId, int amountOfBots)
        {
            try
            {
                long gameId = await _startGameService.CreateGame(playerId, amountOfBots);
                return RedirectToAction("StartRound", new { gameId = gameId });
            }
            catch (Exception ex)
            {
                string message = $"{ex.Source}|{ex.TargetSite}|{ex.StackTrace}|{ex.Message}";
                _logger.Error(message);
                return RedirectToAction("Error", new { message = GameMessageHelper.GameCreationError });
            }
        }

        public async Task<ActionResult> ResumeGame(long playerId)
        {
            try
            {
                long gameId = await _startGameService.ResumeGame(playerId);
                return RedirectToAction("StartRound", new { gameId = gameId });
            }
            catch (Exception ex)
            {
                string message = $"{ex.Source}|{ex.TargetSite}|{ex.StackTrace}|{ex.Message}";
                _logger.Error(message);
                return RedirectToAction("Error", new { message = GameMessageHelper.GameResumingError });
            }
        }

        public async Task<ActionResult> StartRound(long gameId)
        {
            try
            {
                StartGameStartRoundView game = await _startGameService.GetStartGameStartRoundView(gameId);
                return View(game);
            }
            catch (Exception ex)
            {
                string message = $"{ex.Source}|{ex.TargetSite}|{ex.StackTrace}|{ex.Message}";
                _logger.Error(message);
                return RedirectToAction("Error", new { message = GameMessageHelper.GameLoadingError });
            }
        }

        public ActionResult Error(string message)
        {
            return View((object)message);
        }
    }
}

BlackJack.UI/Views/StartGame/AuthorizePlayer.cshtml
@using BlackJack.ViewModels.ViewModels.StartGame;
@model StartGameAuthorizePlayerView
@{
    ViewBag.UserName = Model.Name;
    ViewBag.Title = "Main page";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Main page</h2>
<hr />

<div class="row row-flex">
    @if (Model.ResumeGame)
    {
    <div class="col-lg-6 col-md-6 col-sm-6 col-xs-12 well">
        <h3>Game resuming</h3>
        <p>You can resume your last game</p>
        @Html.ActionLink("Resume game", "ResumeGame", "StartGame", new { playerId = Model.PlayerId }, new { @class = "btn btn-primary" })
    </div>
    }
    <div class="col-lg-6 col-md-6 col-sm-6 col-xs-12 well">
        <h3>Start new game</h3>
        @using (Html.BeginForm("StartNewGame", "StartGame", new { playerId = Model.PlayerId }, FormMethod.Post, new { @class = "form-horizontal" }))
        {
            <div class="form-group">
                <label class="control-label col-md-4">Amount of bots: </label>
                <div class="col-md-8">
                    <input name="amountOfBots" class="form-control" type="number" value="0" min="0" max=5 />
                </div>
            </div>

            <input type="submit" value="Start new game" class="btn btn-primary" />
        }
    </div>
</div>

BlackJack.UI/Views/StartGame/AuthorizedPlayer.cshtml
@using BlackJack.ViewModels.ViewModels;
@using BlackJack.BusinessLogic.Helpers;
@model AuthorizedPlayerViewModel
@{
    ViewBag.UserName = Model.Name;
    ViewBag.Title = "Main page";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Main page</h2>
<hr />

<div class="row row-flex">
    @if (Model.ResumeGame)
    {
    <div class="col-lg-6 col-md-6 col-sm-6 col-xs-12 well">
        <h3>Game resuming</h3>
        <p>You can resume your last game</p>
        @Html.ActionLink("Resume game", "ResumeGame", "StartGame", new { playerId = Model.PlayerId }, new { @class = "btn btn-primary" })
    </div>
    }
    <div class="col-lg-6 col-md-6 col-sm-6 col-xs-12 well">
        <h3>Start new game</h3>
        @using (Html.BeginForm("StartNewGame", "StartGame", new { playerId = Model.PlayerId }, FormMethod.Post, new { @class = "form-horizontal" }))
        {
            <div class="form-group">
                <label class="control-label col-md-4">@GameMessageHelper.BotAmountInput</label>
                <div class="col-md-8">
                    <input name="amountOfBots" class="form-control" type="number" value="0" min="0" max=5 />
                </div>
            </div>

            <input type="submit" value="Start new game" class="btn btn-primary" />
        }
    </div>
</div>

BlackJack.UI/Views/StartGame/Index.cshtml
@using BlackJack.BusinessLogic.Helpers;
@using BlackJack.ViewModels.ViewModels;
@model NameValidationViewModel
@{
    Layout = "~/Views/Shared/_StartPage.cshtml";
    ViewBag.Title = "Home Page";
}

<div class="jumbotron">
    <h1>BlackJack</h1>

    @using (Html.BeginForm("Index", "StartGame", FormMethod.Post, new { @class = "form-horizontal" }))
    {
        <div class="form-group">
            <label class="control-label col-md-2">@GameMessageHelper.NameInput</label>
            <div class="col-md-10">
                @if (!string.IsNullOrEmpty(Model.ValidateMessage))
                {
                    <div class="alert alert-danger">@Model.ValidateMessage</div>
                }
                @Html.TextBoxFor(m => m.UserName, new { @class = "form-control" })
                <br />
                <input type="submit" value="Enter" class="btn btn-primary" />
            </div>
        </div>
    }
</div>

BlackJack.UI/Views/StartGame/MainPage.cshtml
@using BlackJack.ViewModels.ViewModels;
@using BlackJack.BusinessLogic.Helpers;
@model AuthPlayerViewModel
@{
    ViewBag.UserName = Model.Name;
    ViewBag.Title = "Main page";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Main page</h2>
<hr />

<div class="row row-flex">
    @if (Model.ResumeGame)
    {
    <div class="col-lg-6 col-md-6 col-sm-6 col-xs-12 well">
        <h3>Game resuming</h3>
        <p>You can resume your last game</p>
        @Html.ActionLink("Resume game", "ResumeGame", "StartGame", new { playerId = Model.PlayerId }, new { @class = "btn btn-primary" })
    </div>
    }
    <div class="col-lg-6 col-md-6 col-sm-6 col-xs-12 well">
        <h3>Start new game</h3>
        @using (Html.BeginForm("StartNewGame", "StartGame", new { playerId = Model.PlayerId }, FormMethod.Post, new { @class = "form-horizontal" }))
        {
            <div class="form-group">
                <label class="control-label col-md-4">@GameMessageHelper.BotAmountInput</label>
                <div class="col-md-8">
                    <input name="amountOfBots" class="form-control" type="number" value="0" min="0" max=5 />
                </div>
            </div>

            <input type="submit" value="Start new game" class="btn btn-primary" />
        }
    </div>
</div>

BlackJack.UI/Views/StartGame/NameValidation.cshtml
@using BlackJack.BusinessLogic.Helpers;
@using BlackJack.ViewModels.ViewModels;
@model NameValidationViewModel
@{
    Layout = "~/Views/Shared/_StartPage.cshtml";
    ViewBag.Title = "Home Page";
}

<div class="jumbotron">
    <h1>BlackJack</h1>

    @using (Html.BeginForm("NameValidation", "StartGame", FormMethod.Post, new { @class = "form-horizontal" }))
    {
        <div class="form-group">
            <label class="control-label col-md-2">@GameMessageHelper.NameInput</label>
            <div class="col-md-10">
                @if (!string.IsNullOrEmpty(Model.ValidateMessage))
                {
                    <div class="alert alert-danger">@Model.ValidateMessage</div>
                }
                @Html.TextBoxFor(m => m.UserName, new { @class = "form-control" })
                <br />
                <input type="submit" value="Enter" class="btn btn-primary" />
            </div>
        </div>
    }
</div>

BlackJack.UI/Views/StartGame/Round.cshtml
@using BlackJack.ViewModels.ViewModels
@model RoundViewModel
@{
    ViewBag.Title = "Index";
    ViewBag.UserName = Model.Name;
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<input type="hidden" id="gameid" name="gameid" value=@Model.Id />
<input type="hidden" id="stage" name="stage" value="@Model.Stage" />
<input type="hidden" id="userName" value=@Model.Name />
<div id="players">
    <div class="row row-flex">
        <div id="dealer" class="col-lg-4 col-md-4 col-sm-4 col-xs-12 well">
            <input type="hidden" id="dealergameplayerid" name="dealergameplayerid" value=@Model.Dealer.Id />
            <h4><span class="label label-danger">Dealer</span></h4>
            <p>Name: @Model.Dealer.Name</p>
            <div id="dealergameplay">
                <p>Score: @Model.Dealer.Score</p>
            </div>
        </div>

        <div id="human" class="col-lg-8 col-md-8 col-sm-8 col-xs-12 well">
            <div class="row row-flex">
                <div class="col-lg-6 col-md-6 col-sm-6 col-xs-12">
                    <input type="hidden" id="humangameplayerid" name="humangameplayerid" value=@Model.Human.Id />
                    <h4><span class="label label-primary">Human</span></h4>
                    <p>Name: @Model.Human.Name</p>
                    <div id="humangameplay">
                        <p>Score: @Model.Human.Score</p>
                    </div>
                </div>
                <div id="gameplay" class="col-lg-6 col-md-6 col-sm-6 col-xs-12">
                    <label class="control-label">Enter your bet: </label>
                    <input type="number" id="betinput" class="form-control" step="50" min="50" value="50" max=@Model.Human.Score />
                    <br />
                    <input type="submit" class="btn btn-primary" name="betbutton" id="betbutton" value="Enter" />
                </div>
            </div>
        </div>


    </div>

    <div id="bots" class="row row-flex">
        @{ int botCount = 0;}
        @foreach (var bot in Model.Bots)
        {
            <div id="bot" class="col-lg-2 col-md-4 col-sm-4 col-xs-6 well">
                <input type="hidden" id="botgameplayerid@(++botCount)" value=@bot.Id />
                <h4><span class="label label-default">Bot</span></h4>
                <p>Name: @bot.Name</p>

                <div id="botgameplay@(botCount)">
                    <p>Score: @bot.Score</p>
                </div>
            </div>
        }
    </div>
</div>

@Scripts.Render("~/bundles/RoundHandler")

BlackJack.UI/Views/StartGame/StartRound.cshtml
@using BlackJack.ViewModels.ViewModels.StartGame
@model StartGameStartRoundView
@{
    ViewBag.Title = "Index";
    ViewBag.UserName = Model.Human.Name;
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<input type="hidden" id="gameid" name="gameid" value=@Model.Id />
<input type="hidden" id="stage" name="stage" value="@Model.Stage" />
<input type="hidden" id="userName" value=@Model.Human.Name />
<div id="players">
    <div class="row row-flex">
        <div id="dealer" class="col-lg-4 col-md-4 col-sm-4 col-xs-12 well">
            <input type="hidden" id="dealergameplayerid" name="dealergameplayerid" value=@Model.Dealer.Id />
            <h4><span class="label label-danger">Dealer</span></h4>
            <p>Name: @Model.Dealer.Name</p>
            <div id="dealergameplay">
                <p>Score: @Model.Dealer.Score</p>
            </div>
        </div>

        <div id="human" class="col-lg-8 col-md-8 col-sm-8 col-xs-12 well">
            <div class="row row-flex">
                <div class="col-lg-6 col-md-6 col-sm-6 col-xs-12">
                    <input type="hidden" id="humangameplayerid" name="humangameplayerid" value=@Model.Human.Id />
                    <h4><span class="label label-primary">Human</span></h4>
                    <p>Name: @Model.Human.Name</p>
                    <div id="humangameplay">
                        <p>Score: @Model.Human.Score</p>
                    </div>
                </div>
                <div id="gameplay" class="col-lg-6 col-md-6 col-sm-6 col-xs-12">
                    @if (String.IsNullOrEmpty(Model.IsGameOver))
                    {
                        <label class="control-label">Enter your bet: </label>
                        <input type="number" id="betinput" class="form-control" step="50" min="50" value="50" max=@Model.Human.Score />
                        <input type="hidden" id="humanscore" value=@Model.Human.Score />
                        <br />
                        <input type="submit" class="btn btn-primary" name="betbutton" id="betbutton" value="Enter" />
                    }
                    @if (!String.IsNullOrEmpty(Model.IsGameOver))
                    {
                        <p id="gameresult">@Model.IsGameOver</p>
                        <input type="submit" class="btn btn-primary" id="endgame" value="Enter" />
                    }
                </div>
            </div>
        </div>


    </div>

    <div id="bots" class="row row-flex">
        @{ int botCount = 0;}
        @foreach (var bot in Model.Bots)
        {
            <div id="bot" class="col-lg-2 col-md-4 col-sm-4 col-xs-6 well">
                <input type="hidden" id="botgameplayerid@(++botCount)" value=@bot.Id />
                <h4><span class="label label-default">Bot</span></h4>
                <p>Name: @bot.Name</p>

                <div id="botgameplay@(botCount)">
                    <p>Score: @bot.Score</p>
                </div>
            </div>
        }
    </div>
</div>

@Scripts.Render("~/bundles/RoundHandler")

BlackJack.UI/Views/StartGame/ValidateName.cshtml
@using BlackJack.ViewModels.ViewModels.StartGame;
@model StartGameValidateNameView
@{
    Layout = "~/Views/Shared/_StartPage.cshtml";
    ViewBag.Title = "Home Page";
}

<div class="jumbotron">
    <h1>BlackJack</h1>

    @using (Html.BeginForm("ValidateName", "StartGame", FormMethod.Post, new { @class = "form-horizontal" }))
    {
        <div class="form-group">
            <label class="control-label col-md-2">Name: </label>
            <div class="col-md-10">
                @if (!string.IsNullOrEmpty(Model.ValidationMessage))
                {
                    <div class="alert alert-danger">@Model.ValidationMessage</div>
                }
                @Html.TextBoxFor(m => m.UserName, new { @class = "form-control" })
                <br />
                <input type="submit" value="Enter" class="btn btn-primary" />
            </div>
        </div>
    }
</div>