BlackJack.UI/Controllers/StartController.cs
using BlackJack.BusinessLogic.Constants;
using BlackJack.BusinessLogic.Services.Interfaces;
using BlackJack.ViewModels.Start;
using NLog;
using System;
using System.Threading.Tasks;
using System.Web.Mvc;

namespace BlackJack.UI.Controllers
{
    public class StartController : Controller
    {
        private static readonly Logger _logger = LogManager.GetCurrentClassLogger();
        private readonly IStartService _startService;


        public StartController (IStartService startService)
        {
            _startService = startService;
        }
        
        public ActionResult SearchGame()
        {
            return View();
        }

        [HttpPost]
        public async Task<ActionResult> SearchGame(string userName)
        {
            try
            {
                if (String.IsNullOrWhiteSpace(userName))
                {
                    new Exception(GameMessage.ReceivedDataError);
                }

                SearchGameStartView view = await _startService.SearchGame(userName);

                if (view.IsGameExist)
                {
                    return RedirectToAction("Initialize", new { view.GameId, userName });
                }

                return RedirectToAction("CreateGame", new { userName });
            }
            catch (Exception exception)
            {
                string message = exception.ToString();
                _logger.Error(message);
                return RedirectToAction("Display", "Error", new { message = GameMessage.PlayerAuthorizationError });
            }
        }
        
        public ActionResult CreateGame(string userName)
        {
            try
            {
                if(String.IsNullOrWhiteSpace(userName))
                {
                    new Exception(GameMessage.ReceivedDataError);
                }

                var view = new CreateGameStartView();
                view.UserName = userName;
                return View(view);
            }
            catch (Exception exception)
            {
                string message = exception.ToString();
                _logger.Error(message);
                return RedirectToAction("Display", "Error", new { message = GameMessage.GameCreationError });
            }
        }

        [HttpPost]
        public async Task<ActionResult> CreateGame(CreateGameStartView view)
        {
            try
            {
                if (view == null || 
                    String.IsNullOrWhiteSpace(view.UserName))
                {
                    new Exception(GameMessage.ReceivedDataError);
                }

                long gameId = await _startService.CreateGame(view);
                return RedirectToAction("Initialize", new { gameId = gameId, userName = view.UserName, isNewGame = true });
            }
            catch (Exception exception)
            {
                string message = exception.ToString();
                _logger.Error(message);
                return RedirectToAction("Display", "Error", new { message = GameMessage.GameCreationError });
            }
        }
        
        public ActionResult Initialize(long gameId, string userName, bool isNewGame = false)
        {
            try
            {
                var view = new InitializeStartView();
                view.GameId = gameId;
                view.UserName = userName;
                view.IsNewGame = isNewGame;
                return View(view);
            }
            catch (Exception exception)
            {
                string message = exception.ToString();
                _logger.Error(message);
                return RedirectToAction("Display", "Error", new { message = GameMessage.GameLoadingError });
            }
        }
    }
}

BlackJack.UI/Views/Log/Index.cshtml
@model string
@{
    Layout = null;
    ViewBag.Title = "Logs";
}

<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - BlackJack</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    @Styles.Render("~/bundles/KendoUI/css")
    @Scripts.Render("~/bundles/KendoUI/js")
</head>
<body>
    <nav class="navbar navbar-default">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#myNavbar">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Home", "AuthorizePlayer", "Start", new { userName = Model }, new { @class = "navbar-brand" })
            </div>

            <div class="collapse navbar-collapse" id="myNavbar">
                <ul class="nav navbar-nav">
                    <li class="nav-item">
                        @Html.ActionLink("Game logs", "Index", "Log", new { userName = Model }, null)
                    </li>
                </ul>
                <ul class="nav navbar-nav navbar-right">
                    <li class="navbar-text">
                        <b>Log in as: @Model</b>
                    </li>
                    <li class="nav-item">
                        @Html.ActionLink("Log out", "ValidateName", "Start")
                    </li>
                </ul>
            </div>
        </div>
    </nav>
    <div class="container body-content">
        <h2>Logs</h2>
        <div id="grid"></div>
        @Scripts.Render("~/bundles/KendoUI/Logs")
        <hr />
    </div>

    @Scripts.Render("~/bundles/bootstrap")
</body>
</html>